version: '3'
services:
  gateway:
      profiles: ["not-dev"]

  api:
    profiles: [ "not-dev", "api", "api-etl" ]
    ports:
      - "8000:8000"

  etl:
    profiles: [ "etl", "api-etl" ]

  theatre-db:
    ports:
      - "5432:5432"
    volumes:
      - ./tools/database_dump.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    ports:
      - "6379:6379"

  elasticsearch:
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms200m -Xmx200m